### ISSUE TITLE
주말간 이슈사항

### ISSUE THREAD

**Issue by wolframhwang** [wolframhwang/CRA22_7#21]

**Comment by wolframhwang** [comment]
@sh0610-han 상훈님.
Condition 관련된 부분의 Employee는 EmployeeInfo를 사용함이 맞아보입니다.
확인부탁드리겠습니다.

**Comment by sh0610-han** [comment]
@wolframhwang 지웅님,
수정에 앞서 확인차 문의드립니다. Employee.h 파일 내 Employee, EmployeeInfo 두 가지 정의가 존재하는데요
둘 중 하나만 사용해도 충분하지 않을까요??
그렇다면 둘 중 하나의 이름으로 통일하는 편이 좋아보입니다.

**Comment by sh0610-han** [comment]
Employee 관련 코드 정리를 진행하면서 Condition쪽도 함께 해결하겠습니다.
